<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;


class User extends Authenticatable
{
    /** @use HasFactory<\Database\Factories\UserFactory> */
    use HasFactory, Notifiable, SoftDeletes;


    /**
     * @var mixed|string
     */
    /**
     * @property string $name
     * @property string $email
     * @property string $password
     * @property string $slug
     * @property integer $id
     * @property integer $age
     * @property boolean $active
     * @property integer $role_id
     */
    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'active',
        'age',
        'slug',
        'role_id',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];


    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }

      public function phones() : HasMany
    {
        return $this->hasMany(Phone::class);
    }
    public function books() : HasMany
    {
        return $this->hasMany(Book::class);
    }

    public function avatar() : HasOne
    {
        return $this->hasOne(Avatar::class);
    }
    public function musics(): BelongsToMany
    {
        return $this->belongsToMany(Music::class);
    }

    public function role (): BelongsTo
    {
        return $this->belongsTo(Role::class);
    }

//    public function favoriteMusic(): BelongsToMany
//    {
//        return $this->belongsToMany(Music::class, 'favorites')->withTimestamps();
//
//    }

    public function scopeSlug($query, $slug)
    {
        return $query->where('slug', $slug);
    }

    //Mutator
    public function setNameAttribute(string $name) : void
    {
        $this->attributes['name'] = Str::ucfirst($name);
    }
    //Акцессор
    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }
}

